CREATE TABLE USER (
    Phone_Number VARCHAR(15) NOT NULL UNIQUE,
    First_Name VARCHAR(50) NOT NULL,
    Last_Name VARCHAR(50) NOT NULL,
    Password VARCHAR(20) NOT NULL,
    PRIMARY KEY (Phone_Number)
);

CREATE TABLE DEVICE (
	ID INTEGER NOT NULL,
    Logged_in_status BOOL,
    Phone_Number VARCHAR(15) NOT NULL,
    FOREIGN KEY (Phone_Number) REFERENCES USER (Phone_Number) ON UPDATE CASCADE
);

CREATE TABLE CHAT (
    ID INTEGER NOT NULL UNIQUE,
    Name VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PARTICIPANTS (
	Phone_Number VARCHAR(15) NOT NULL,
    Chat_ID INTEGER NOT NULL,
    FOREIGN KEY (Phone_Number) REFERENCES USER (Phone_Number) ON UPDATE CASCADE,
    FOREIGN KEY (Chat_ID) REFERENCES CHAT (ID) ON UPDATE CASCADE
);

CREATE TABLE MESSAGE (
	ID INTEGER NOT NULL UNIQUE,
    Date_Sent DATE,
    Time_Sent TIME,
    Text VARCHAR(500),
    Chat_ID INTEGER NOT NULL,
	Sender_Phone_Number VARCHAR(15) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (Chat_ID) REFERENCES CHAT (ID) ON UPDATE CASCADE,
    FOREIGN KEY (Sender_Phone_Number) REFERENCES USER (Phone_Number) ON UPDATE CASCADE
);

CREATE TABLE MEDIA (
	ID INTEGER NOT NULL UNIQUE,
	Directory VARCHAR(512) NULL,
    Message_ID INTEGER NOT NULL,
    FOREIGN KEY (Message_ID) REFERENCES MESSAGE (ID) ON UPDATE CASCADE
);
