
CREATE TABLE USER (
    Phone_Number VARCHAR(15),
    First_Name VARCHAR(50) NOT NULL,
    Last_Name VARCHAR(50) NOT NULL,
    Password VARCHAR(20) NOT NULL,
    PRIMARY KEY (Phone_Number)
);

CREATE TABLE DEVICE (
	ID INTEGER NOT NULL,
    Logged_in_status BOOL,
    Phone_Number VARCHAR(15) NOT NULL,
    FOREIGN KEY (Phone_Number) REFERENCES USER (Phone_Number) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CHAT (
    ID INTEGER,
    Name VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PARTICIPANTS (
	Phone_Number VARCHAR(15) NOT NULL,
    Chat_ID INTEGER NOT NULL,
    FOREIGN KEY (Phone_Number) REFERENCES USER (Phone_Number) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Chat_ID) REFERENCES CHAT (ID) ON UPDATE RESTRICT ON DELETE CASCADE
);

CREATE TABLE MESSAGE (
	ID INTEGER,
    DateTime_Sent DATETIME,
    Text VARCHAR(500),
    Chat_ID INTEGER NOT NULL,
	Sender_Phone_Number VARCHAR(15),
    PRIMARY KEY (ID),
    FOREIGN KEY (Chat_ID) REFERENCES CHAT (ID) ON UPDATE RESTRICT ON DELETE CASCADE,
    FOREIGN KEY (Sender_Phone_Number) REFERENCES USER (Phone_Number) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE MEDIA (
	ID INTEGER NOT NULL UNIQUE,
	Directory VARCHAR(512) NOT NULL,
    Message_ID INTEGER NOT NULL,
    FOREIGN KEY (Message_ID) REFERENCES MESSAGE (ID) ON UPDATE RESTRICT ON DELETE CASCADE
);


