SELECT * FROM USER;
SELECT * FROM DEVICE;
SELECT * FROM CHAT;
SELECT * FROM PARTICIPANTS;
SELECT * FROM MESSAGE;
SELECT * FROM MEDIA;

SELECT * FROM USER_VIEW;
SELECT * FROM MESSAGES_IN_CHAT;
SELECT * FROM PARTICIPANTS_DETAILS;

SELECT name FROM chat, participants
WHERE participants.phone_number = '4965609651' AND participants.Chat_ID=chat.ID;
